spring.application.name=healthcare-app
spring.profiles.active=dev
# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db
spring.datasource.username=root
spring.datasource.password=Suryawanshi@777

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# JWT CONFIGURATION
# ===============================
app.jwt.secret=MyHealthcareAppSecretKeyForJWTAuthentication2026VeryLongSecureKey

# ===============================
# FILE UPLOAD CONFIGURATION
# ===============================
app.upload.dir=uploads

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080